spring:
  application:
    name: MediaSoftJavaEECityGuide
  datasource:
    url: 'jdbc:postgresql://localhost/MediaSoftJavaEECityGuide'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'
    enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: '90'
springdoc:
  show-login-endpoint: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

app:
  version: 0.1
  description: "API путеводителя по городским достопримечательностям"
